### ISSUE TITLE
[PR] Checklist v0.1.0

### ISSUE THREAD

**Issue by BillyBlaze** [BillyBlaze/OctoPrint-TouchUI#2]
**Features/Styling**
- [X] Mimick mousepointer events as Touch
- [X] Add virtual keyboard if no touch device
- [X] Printer tab
  - [X] Move connection state into this tab
  - [X] Remove scrollSomething module
  - [X] Swipe to left in files list for more actions
- [X] Temperature tab
  - [X] Swipe to left for offset temps
- [X] Controls tab
  - [X] Move feed & flow rate into the same div
  - [X] Remove sliders and use input
- [x] Webcam tab **testing needed->keyboard controls still working?**
- [X] Terminal tab
  - [X] ASCII header
  - [X] Version check
  - [X] Scroll touch (if scrollbar)
- [x] Timelapse tab
  - [x] Style the table and actions
- [x] Navbar
  - [x] Clone all tab items, hide the original, bind clones to original tab (DOM.js, lines 122)
- [X] GCode viewer
- [X] Modals
  - [X] Scroll touch on open
  - [X] Dropdown navigation
  - [X] Leftside orientated full-height modal
  - [X] Remove scrollSomething module
  - [X] Fullwidth views
- [X] Notifications
- [X] Dialog screens (i.e. reload needed, offline)
- [X] Write all JS to jQuery plugin
- [X] Compile LESS with Gulp and serve CSS for better performance
- [X] Register to OctoPrint version checking
- [X] Use the latest FontAwesome for more icons
- [x] LESS
  - [x] Add most common variables into a seperate _variable file
- [x] Add a fullscreen toggle mode

**Known bugs**
- [X] Move ASCII art into a webfont
- [X] No-pointer class doesn't get remove from dropdown, causing no navigation possible
- [X] Mobile navigationbar makes VH units jump
- [X] Refactor virtual keyboard to attach keyboard to dynamic content rather then only on DOMLoad

**Cross-browser**
- [x] Test as many devices as possible
  - [X] Chrome 45.0.2454.101 m
  - [X] Firefox 41.0.1
  - [x] Raspberry Pi (1) / Iceweavel
  - [x] Raspberry Pi (2) / Iceweavel
  - [x] Android phone
    - [X] Nexus 5 / Android 4.x / Chrome
  - [x] Android tablet
    - [X] Nexus 7 / Android 4.x / Chrome (45)
  - [x] iOS
    - [x] iPhone 6 / Safari
  - [x] IE
    - [x] Windows 10 / Edge - Non-touch
    - [x] Windows 10 / Edge - Touch
- [x] Ask community for beta testing

**Register Plugin repository**
- [x] Clone repo
- [x] Add content
  - [x] Screenshots from devices
- [x] Request merge

**Comment by Akex2** [comment]
The plugin won't install on my raspberry
![image](https://cloud.githubusercontent.com/assets/8688892/10277826/19ab64e4-6b59-11e5-9f72-621675593439.jpg)

![image](https://cloud.githubusercontent.com/assets/8688892/10277859/503cb81e-6b59-11e5-9f44-47e210cce582.jpg)

Thx

**Comment by BillyBlaze** [comment]
Awesome thanks, I just merged a merge-request, could you try it again?

**Comment by Akex2** [comment]
Hy
In the temperature tab can you make just number keyboard, now there are azerty keyboard
Thx
And the temperature of raspberry and bed and extruder, can you make two line because i can click on terminal tab i think is that
Thanks billy work fine ;)

**Comment by satoer** [comment]
Hi Billy,

Thanks for sharing this plugin. I’m looking if I can use it to make a printer completely standalone with a nifty LCD. But I think the plugin has some bugs:
There’s no way I can go to the settings menu. On every client I try the configuration icon is not where it supposed to be (according to screenshots). If I press the upper right corner only the shutdown and restart options appear.
![octoprint-touchui-bug](https://cloud.githubusercontent.com/assets/15175433/10561342/e1f17dec-7524-11e5-93da-c1f0ead9ffce.jpg)

This is with the latest versions of Firefox, IE, Chrome, Iceweasel and safari on the ipad (this is an ipad screenshot)

And bug number 2: On the (non TouchUI) configuration page the “Open the user settings” button does nothing. The only way to activate TouchUI is: octopi.local/#touch And for now the only way to disable it is to remove cookies.

Regards, Michel
